apiVersion: v1
kind: Pod
metadata:
  name: epx-ui-pod
  labels:
    component: web
spec:
  containers:
  - name: epx-ui
    image: ranjithrajd/epx-ui:latest
    ports:
    - containerPort: 9090
    resources:
      limits:
        memory: "900Mi"
        cpu: "900m"
      requests:
        memory: "700Mi"
        cpu: "600m"